---
title: What The Fuck Just Happened Today?
timezone: America/Los_Angeles
collections:
  authors:
    title: Authors
    output: true
  guide:
    title: Guides
    output: false
  notes:
    title: Notes
    output: false
  podcasts:
    title: Podcasts
    output: false
  posts:
    title: Posts
    output: true
  topics:
    title: Topics
    output: true
  uploads:
    title: Uploads
    output: false
  wtfis:
    title: WTFis
    output: true
defaults:
- scope:
    path: ''
    type: WTFis
  values:
    title: ''
    description: ''
    permalink: "/:title/"
    image: ''
    author: Matt Kiser
    layout: wtfis
    seo:
      type: NewsArticle
      name: What The Fuck Just Happened Today?
      description: Your essential guide to the shock and awe in national politics.
        A sane, once-a-day newsletter helping normal people make sense of the news.
- scope:
    path: ''
    type: posts
  values:
    title: ''
    description: ''
    image: ''
    todayInOneSentence: ''
    author: Matt Kiser
    layout: post
    seo:
      type: NewsArticle
      name: What The Fuck Just Happened Today?
      description: Your essential guide to the shock and awe in national politics.
        A sane, once-a-day newsletter helping normal people make sense of the news.
      links:
      - https://whatthefuckjusthappenedtoday.com/
      - https://twitter.com/WTFJHT
      - https://www.instagram.com/wtfjht/
      - https://bsky.app/profile/wtfjht.bsky.social
      - https://www.threads.net/@wtfjht
      - https://mastodon.social/@wtfjht
      - https://www.facebook.com/wtfjht
      - https://github.com/mkiser/WTFJHT
- scope:
    path: ''
    type: notes
  values:
    permalink: "/:year/:month/:day/latest/"
    title: ''
    description: ''
    image: https://whatthefuckjusthappenedtoday.com/public/wtfjht-f.jpg
    flag: The Latest.
    is_promoted: false
    layout: note
    sitemap: false
- scope:
    path: ''
    type: authors
  values:
    permalink: "/author/:title/"
    layout: author
    twitter: 
    email: 
    seo:
      type: Person
      links:
      - https://whatthefuckjusthappenedtoday.com/
      - https://twitter.com/WTFJHT
      - https://www.instagram.com/wtfjht/
      - https://bsky.app/profile/wtfjht.bsky.social
      - https://www.threads.net/@wtfjht
      - https://mastodon.social/@wtfjht
      - https://www.facebook.com/wtfjht
      - https://github.com/mkiser/WTFJHT
- scope:
    path: ''
    type: podcasts
  values:
    title: 
    file: 
    post: 
    duration: 
    length: 
    author: Joe Amditis
    image: "/public/wtf-pod.jpg"
    tags:
    - politics
    - news
    sitemap: false
- scope:
    path: page
  values:
    sitemap: false
- scope:
    path: ''
    type: topics
  values:
    permalink: "/:title/"
    title: ''
    description: ''
    image: ''
    author: Matt Kiser
    layout: topics
    seo:
      type: NewsArticle
is_away_mode: false
permalink: pretty
name: What The Fuck Just Happened Today?
tagline: Your essential guide to the shock and awe in national politics. A sane, once-a-day
  newsletter helping normal people make sense of the news.
description: Your essential guide to the shock and awe in national politics. A sane,
  once-a-day newsletter helping normal people make sense of the news.
url: https://whatthefuckjusthappenedtoday.com
baseurl: 
source: "."
destination: "./_site"
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
lsi: false
twitter:
  username: WTFJHT
encoding: utf-8
markdown: CommonMark
commonmark:
  extensions:
  - strikethrough
  options:
  - SMART
  - UNSAFE
  - FOOTNOTES
incremental: true
social:
  name: Matt Kiser
  links:
  - https://twitter.com/matt_kiser
  - https://www.facebook.com/mattkiser
  - https://www.linkedin.com/in/mattkiser
  - https://github.com/mkiser
  - https://whatthefuckjusthappenedtoday.com/
  - https://twitter.com/WTFJHT
  - https://www.instagram.com/wtfjht/
  - https://bsky.app/profile/wtfjht.bsky.social
  - https://www.threads.net/@wtfjht
  - https://mastodon.social/@wtfjht
  - https://www.facebook.com/wtfjht
logo: "/public/wtfjht-f.jpg"
author:
  twitter: matt_kiser
  name: Matt Kiser
  url: https://whatthefuckjusthappenedtoday.com
  email: matt@whatthefuckjusthappenedtoday.com
  links:
  - https://twitter.com/matt_kiser
  - https://www.facebook.com/mattkiser
  - https://www.linkedin.com/in/mattkiser
  - https://github.com/mkiser
  - https://whatthefuckjusthappenedtoday.com/
  - https://twitter.com/WTFJHT
  - https://www.instagram.com/wtfjht/
  - https://bsky.app/profile/wtfjht.bsky.social
  - https://www.threads.net/@wtfjht
  - https://mastodon.social/@wtfjht
  - https://www.facebook.com/wtfjht
facebook:
  app_id: 601457263382211
  publisher: 1415262761838827
  admins: 29904434
sass:
  sass_dir: _sass
  style: compressed
version: 1.0.0
github:
  repo: https://github.com/mkiser/WTFJHT
exclude:
- _notes
- ".jekyll-cache"
- vendor
- Gemfile
- Gemfile.lock
- README.md
- meta
- guide
algolia:
  application_id: UI0QYYDNB1
  index_name: WTFJHT
  read_only_api_key: 50fe80eaf3c61b236fe7408e8be4bc30
  max_record_size: 20000
  nodes_to_index: p
  extensions_to_index: html,md,markdown
  files_to_exclude:
  - 404.html
  - about.md
  - all.html
  - archive.md
  - archive.html
  - archives
  - atom.xml
  - faq.md
  - index.html
  - membership.html
  - press.md
  - rss.xml
  - styles.css
  - subscribe.md
  - survey.md
  - team.md
  - today.html
  - whitelist.html
  - yesterday.html
  - license.html
  - license.txt
  - almost.html
  - trump-epa.markdown
  - trump-fake-news.markdown
  - trump-health-care.markdown
  - trump-russia-investigation.markdown
  - trump-travel-ban.markdown
  - trump-epa
  - trump-fake-news
  - trump-health-care
  - trump-russia-investigation
  - trump-travel-ban
  - first-100-days
  - first-100-days.html
  - faq
  - license
  - pee-tape.html
  - quiz.html
  - do-something/*
  - meta/*
  - 45-for-45/*
  - _authors/*
  - _podcasts/*
  - podcasts/index.html
  - guide/*
  - _topics/*
  - _notes/*
  - _topics/*.markdown
  - _whatwelearned/*
  - page/*/**.html
  - donald-trumps-impeachment-from-whistleblower-to-acquittal.markdown
  - trump-impeachment-news-timeline-analysis.html
  settings:
    searchableAttributes:
    - unordered(content)
    - date
    - title
    customRanking:
    - desc(custom_ranking.heading)
    - asc(custom_ranking.position)
    distinct: false
extlinks:
  attributes:
    target: _blank
    rel: noopener
    class: external
  rel_exclude:
  - whatthefuckjusthappenedtoday.com
jekyll_admin:
  hidden_links:
  - pages
  - staticfiles
  - datafiles
  - configuration
jekyll-archives:
  enabled:
  - year
  - month
  layouts:
    year: year-archive
    month: month-archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
plugins:
- jekyll-redirect-from
- jekyll-commonmark
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-extlinks
- jekyll-archives
- jekyll-include-cache
- jekyll-algolia
podcast_album_art: "/podcasts/wtfpod.jpg"
podcast_title: WTF Just Happened Today
podcast_owner: Matt Kiser
podcast_email: matt@whatthefuckjusthappenedtoday.com
podcast_category: News
podcast_subcategory: Politics
podcast_explicit: Clean
podcast_author: Matt Kiser
podcast_description: A sane, once-a-day update on today’s essential political news.
  Chronicling the daily shock and awe since 2017.
podcast_summary: A sane, once-a-day update on today’s essential political news. Chronicling
  the daily shock and awe since 2017.
podcast_subtitle: 
podcast_copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  License.
cloudfront_url: https://d3ur8zm5qs6awd.cloudfront.net
