# Permalinks
permalink:           pretty

# collections:
#   guides:
#     output: true
#     permalink: pretty
    
# Setup
title:            What The Fuck Just Happened Today?
name:             "What The Fuck Just Happened Today?"
tagline:          "Today's essential newsletter. Logging the daily shock and awe in national politics. Read in moderation."
description:      "Today's essential newsletter. Logging the daily shock and awe in national politics. Read in moderation."
url:              "https://whatthefuckjusthappenedtoday.com"
baseurl:          ""
twitter:
  username: WTFJHT


facebook:
  app_id: 601457263382211

ampdir: amp

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
# About/contact
# author:
#   name:             'Matt Kiser'
#   url:              'https://whatthefuckjusthappenedtoday.com'
#   email:            'matt@whatthefuckjusthappenedtoday.com'

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/mkiser/WTFJHT
timezone:            America/Los_Angeles
exclude:             [vendor]

algolia:
  application_id: 'UI0QYYDNB1'
  index_name:     'WTFJHT'
  read_only_api_key: '50fe80eaf3c61b236fe7408e8be4bc30'
  record_css_selector: 'p,li,blockquote'
  excluded_files:
    - 404.html
    - about.md
    - faq.md
    - index.html
    - membership.md
    - press.md
    - rss.xml
    - atom.xml
    - styles.css

# Gems
gems:
  - jekyll-gist
  - github-pages
  - jekyll-seo-tag
  - jekyll-sitemap
  - algoliasearch-jekyll
  # - amp-jekyll