---
title: What The Fuck Just Happened Today?
timezone: America/Los_Angeles
collections:
  authors:
    title: Authors
    output: true
  notes:
    title: Notes
    output: true
  podcasts:
    title: Podcasts
    output: true
  posts:
    title: Posts
    output: true
  topics:
    title: Topics
    output: true
  uploads:
    title: Uploads
    output: true
  whatwelearned:
    title: What We Learned
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    title: ''
    description: ''
    image: ''
    todayInOneSentence: ''
    author: Matt Kiser
    layout: post
    seo:
      type: NewsArticle
- scope:
    path: ''
    type: whatwelearned
  values:
    permalink: "/what-we-learned/:year/:month/:title/"
    title: ''
    description: What We Learned in the Russia Probe
    image: ''
    author: Adrienne Cobb
    is_promoted: false
    layout: whatwelearned
    seo:
      type: NewsArticle
- scope:
    path: ''
    type: notes
  values:
    permalink: "/:year/:month/:day/latest/"
    title: ''
    description: ''
    image: ''
    flag: The Latest.
    is_promoted: false
    layout: note
    metatags: noindex, follow
    sitemap: false
- scope:
    path: ''
    type: authors
  values:
    permalink: "/author/:title/"
    layout: author
    twitter: 
    email: 
    metatags: noindex, follow
    sitemap: false
- scope:
    path: ''
    type: podcasts
  values:
    permalink: "/:year/:month/:day/podcast/"
    layout: pod
    title: 
    file: 
    post: 
    duration: 
    length: 
    author: Joe Amditis
    image: "/public/wtf-pod.jpg"
    tags:
    - politics
    - news
    metatags: noindex, follow
    sitemap: false
- scope:
    path: ''
    type: topics
  values:
    permalink: "/:title/"
    title: ''
    description: ''
    image: ''
    author: Matt Kiser
    layout: topics
    seo:
      type: NewsArticle
- scope:
    path: page
  values:
    sitemap: false
    metatags: noindex, follow
permalink: pretty
name: What The Fuck Just Happened Today?
tagline: Today's essential guide to the daily shock and awe in national politics.
  Read in moderation.
description: Today's essential guide to the daily shock and awe in national politics.
  Read in moderation.
url: https://whatthefuckjusthappenedtoday.com
baseurl: 
source: "."
destination: "./_site"
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
paginate: 1
paginate_path: "/page/:num/"
twitter:
  username: WTFJHT
encoding: utf-8
kramdown:
  smart_quotes:
  - apos
  - apos
  - quot
  - quot
social:
  name: Matt Kiser
  links:
  - https://twitter.com/matt_kiser
  - https://www.facebook.com/mattkiser
  - https://www.linkedin.com/in/mattkiser
  - https://github.com/mkiser
logo: "/public/wtfjht-f.jpg"
author:
  twitter: matt_kiser
  name: Matt Kiser
  url: https://whatthefuckjusthappenedtoday.com
  email: matt@whatthefuckjusthappenedtoday.com
facebook:
  app_id: 601457263382211
  publisher: 1415262761838827
  admins: 29904434
ampdir: amp
sass:
  sass_dir: _sass
  style: compressed
version: 1.0.0
github:
  repo: https://github.com/mkiser/WTFJHT
exclude:
- vendor
- Gemfile
- Gemfile.lock
- CONTRIBUTING.md
- README.md
algolia:
  application_id: UI0QYYDNB1
  index_name: WTFJHT
  read_only_api_key: 50fe80eaf3c61b236fe7408e8be4bc30
  nodes_to_index: p
  extensions_to_index: html,md,markdown
  files_to_exclude:
  - 404.html
  - about.md
  - all.html
  - archive.md
  - archive.html
  - archives
  - atom.xml
  - faq.md
  - index.html
  - instant-feed.xml
  - instantfeed.xml
  - membership.html
  - press.md
  - rss.xml
  - styles.css
  - subscribe.md
  - survey.md
  - team.md
  - today.html
  - whitelist.html
  - yesterday.html
  - license.html
  - license.txt
  - almost.html
  - trump-epa.markdown
  - trump-fake-news.markdown
  - trump-health-care.markdown
  - trump-russia-investigation.markdown
  - trump-travel-ban.markdown
  - trump-epa
  - trump-fake-news
  - trump-health-care
  - trump-russia-investigation
  - trump-travel-ban
  - first-100-days
  - first-100-days.html
  - faq
  - license
  - pee-tape.html
  - quiz.html
  - do-something/*
  - meta/*
  - 45-for-45/*
  - _authors/*
  - _podcasts/*
  - podcasts/index.html
  - guide/*
  - _topics/*
  - _notes/*
  - _topics/*.markdown
  - page/*/**.html
  settings:
    searchableAttributes:
    - unordered(content)
    - date
    - title
    customRanking:
    - desc(custom_ranking.heading)
    - asc(custom_ranking.position)
    distinct: false
extlinks:
  attributes:
    target: _blank
    rel: noopener
    class: external
  rel_exclude:
  - whatthefuckjusthappenedtoday.com
jekyll_admin:
  hidden_links:
  - pages
  - staticfiles
  - datafiles
  - configuration
jekyll-archives:
  enabled:
  - year
  - month
  layouts:
    year: year-archive
    month: month-archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
plugins:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-extlinks
- jekyll-archives
- jekyll-include-cache
- jekyll-onebox
- jekyll-algolia
onebox:
  whitelist:
  - nbcnews.com
  - politico.com
  - thedailybeast.com
  - thehill.com
  - vox.com
  - cnbc.com
  - apnews.com
  - theguardian.com
  - buzzfeed.com
  - abcnews.go.com
  - reuters.com
  - theverge.com
podcast_album_art: "/podcasts/wtfpod.jpg"
podcast_title: WTF Just Happened Today
podcast_owner: Matt Kiser
podcast_email: matt.kiser@gmail.com
podcast_category: News &amp; Politics
podcast_explicit: Clean
podcast_author: Matt Kiser
podcast_description: Your essential guide to the daily shock and awe in national politics.
podcast_summary: Your essential guide to the daily shock and awe in national politics.
podcast_subtitle: 
podcast_copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  License.
cloudfront_url: https://d3ur8zm5qs6awd.cloudfront.net
