# Permalinks
permalink:           pretty

# Setup
title:            What The Fuck Just Happened Today?
name:             "What The Fuck Just Happened Today?"
tagline:          "Today's essential newsletter. Logging the daily shock and awe in national politics. Read in moderation."
description:      "Today's essential newsletter. Logging the daily shock and awe in national politics. Read in moderation."
url:              "https://whatthefuckjusthappenedtoday.com"
baseurl:          ""
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
twitter:
  username: WTFJHT

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

social:
  name: Matt Kiser
  links:
    - https://twitter.com/matt_kiser
    - https://www.facebook.com/mattkiser
    - https://www.linkedin.com/in/mattkiser
    - https://github.com/mkiser

# About/contact
# author:
#   name:             'Matt Kiser'
#   url:              'https://whatthefuckjusthappenedtoday.com'
#   email:            'matt@whatthefuckjusthappenedtoday.com'

facebook:
  app_id: 601457263382211

ampdir: amp

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/mkiser/WTFJHT
timezone:            America/Los_Angeles
exclude:             [vendor]

algolia:
  application_id: 'UI0QYYDNB1'
  index_name:     'WTFJHT'
  read_only_api_key: '50fe80eaf3c61b236fe7408e8be4bc30'
  record_css_selector: 'p,li,blockquote'
  excluded_files:
    - 404.html
    - about.md
    - all.html
    - archive.md
    - atom.xml
    - faq.md
    - first-100-days.html
    - index.html
    - instant-feed.xml
    - instantfeed.xml
    - membership.md
    - press.md
    - rss.xml
    - styles.css
    - subscribe.md
    - survey.md
    - team.md
    - today.html
    - whitelist.html
    - yesterday.html

extlinks:
  attributes: {target: _blank, rel: noopener, class: external}
  rel_exclude: ['whatthefuckjusthappenedtoday.com']

# Gems
gems:
  - jekyll-gist
  - jekyll-redirect-from
  - github-pages
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - amp-jekyll
  - jekyll-twitter-plugin
  - jekyll-extlinks
  # - jekyll-admin