---
title: What The Fuck Just Happened Today?
timezone: America/Los_Angeles
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  wtf-is:
    title: WTFis
    output: false
defaults:
- scope:
    path: ''
    type: wtf-is
  values:
    title: ''
    description: ''
    tags: ''
    permalink: "/wtf-is/:title/"
    image: ''
    author: Matt Kiser
    layout: wtfis
    seo:
      type: NewsArticle
      name: What The Fuck Just Happened Today?
      description: Your essential guide to the shock and awe in national politics.
        A sane, once-a-day newsletter helping normal people make sense of the news.
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:year/:month/:day/:title/"
    title: ''
    description: ''
    image: ''
    todayInOneSentence: ''
    author: Matt Kiser
    layout: post
    tag_excerpts: ''
    category: trump
    podcast:
      file: ''
      duration: ''
      length: ''
      transcript: ''
    seo:
      type: NewsArticle
      name: What The Fuck Just Happened Today?
      description: Your essential guide to the shock and awe in national politics.
        A sane, once-a-day newsletter helping normal people make sense of the news.
      links:
      - https://whatthefuckjusthappenedtoday.com/
      - https://x.com/WTFJHT
      - https://www.instagram.com/wtfjht/
      - https://bsky.app/profile/whatthefuckjusthappenedtoday.com
      - https://www.threads.net/@wtfjht
      - https://mastodon.social/@wtfjht
      - https://www.facebook.com/wtfjht
      - https://github.com/mkiser/WTFJHT
- scope:
    path: ''
    type: authors
  values:
    permalink: "/author/:title/"
    layout: author
    twitter: 
    email: 
    seo:
      type: Person
      links: 
- scope:
    path: page
  values:
    sitemap: false
- scope:
    path: ''
    type: topics
  values:
    permalink: "/:title/"
    title: ''
    description: ''
    image: ''
    author: Matt Kiser
    layout: topics
    seo:
      type: NewsArticle
name: What The Fuck Just Happened Today?
tagline: Political News for Normal People.
description: Your essential guide to the shock and awe in national politics. A sane,
  once-a-day newsletter helping normal people make sense of the news.<br>Read in moderation.
is_away_mode: false
is_doomsday_counter: false
permalink: pretty
url: https://whatthefuckjusthappenedtoday.com
baseurl: 
source: "."
destination: "./_site"
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
lsi: false
twitter:
  username: WTFJHT
encoding: utf-8
markdown: CommonMark
commonmark:
  extensions:
  - strikethrough
  options:
  - SMART
  - UNSAFE
  - FOOTNOTES
incremental: true
social:
  name: Matt Kiser
  links:
  - https://twitter.com/matt_kiser
  - https://www.facebook.com/mattkiser
  - https://www.linkedin.com/in/mattkiser
  - https://github.com/mkiser
logo: "/og-image.jpg?v=3"
author:
  twitter: matt_kiser
  name: Matt Kiser
  url: https://whatthefuckjusthappenedtoday.com
  email: matt@whatthefuckjusthappenedtoday.com
  links:
  - https://twitter.com/matt_kiser
  - https://www.facebook.com/mattkiser
  - https://www.linkedin.com/in/mattkiser
  - https://github.com/mkiser
facebook:
  app_id: 601457263382211
  publisher: 1415262761838827
  admins: 29904434
sass:
  sass_dir: _sass
  style: compressed
version: 1.0.0
github:
  repo: https://github.com/mkiser/WTFJHT
exclude:
- _notes
- ".jekyll-cache"
- vendor
- Gemfile
- Gemfile.lock
- README.md
- meta
- guide
- _podcasts
- _topics
extlinks:
  attributes:
    target: _blank
    rel: noopener
    class: external
  rel_exclude:
  - whatthefuckjusthappenedtoday.com
jekyll_admin:
  hidden_links:
  - pages
  - staticfiles
  - datafiles
  - configuration
jekyll-archives:
  enabled:
  - year
  - month
  layouts:
    year: year-archive
    month: month-archive
  permalinks:
    year: "/archive/:year/"
    month: "/archive/:year/:month/"
plugins:
- jekyll-redirect-from
- jekyll-commonmark
- jekyll-sitemap
- jekyll-extlinks
- jekyll-archives
- jekyll-include-cache
podcast_album_art: "/podcast-3000x3000.png?v=3"
podcast_title: WTF Just Happened Today? – Audio Edition
podcast_owner: Matt Kiser
podcast_email: matt@whatthefuckjusthappenedtoday.com
podcast_category: News
podcast_subcategory: Politics
podcast_explicit: false
podcast_author: Matt Kiser
podcast_description: A sane, once-a-day update on today’s essential political news.
  Chronicling the daily shock and awe since 2017.
podcast_summary: A sane, once-a-day update on today’s essential political news. Chronicling
  the daily shock and awe since 2017.
podcast_subtitle: 
podcast_copyright: CC BY-NC-SA 4.0
cloudfront_url: https://d3ur8zm5qs6awd.cloudfront.net
podcast_guid: 0C736D1F-59A8-4176-AFDA-D4111EF9DC61
podcast_links:
  apple: https://podcasts.apple.com/us/podcast/wtf-just-happened-today/id1206537023
  spotify: https://open.spotify.com/show/5AjVGcr9p8LZFOjJKOw4b3
  youtube: https://www.youtube.com/@WTFJHT/podcasts
  rss: "/podcasts/index.xml"
